### ISSUE TITLE
Email sponsorship contact form

### ISSUE THREAD

**Issue by GageLochner** [m2i/MAVRIC-General#18]
[Email Contact Template.docx](https://github.com/m2i/MAVRIC-General/files/1308762/Email.Contact.Template.docx)

Looking for anyone to provide input or edits.

**Comment by dwhited** [comment]
[Email.Contact.Template.Derick.Comments.docx](https://github.com/m2i/MAVRIC-General/files/1309411/Email.Contact.Template.Derick.Comments.docx)

Here's the document with my comments attached.

**Comment by GageLochner** [comment]
Comments attended to. Will continue to modify according to suggestions until the form is used for the first time. All spaces in yellow are to be filled out according to who you are contacting.

Thanks
