### ISSUE TITLE
Website update process

### ISSUE THREAD

**Issue by GageLochner** [m2i/MAVRIC-General#20]
Assigning Gabe, Isaiah, and myself to the website update, which is due on the 20th of October. See the project listing, which I would link if I could figure out how to that.

**Comment by isa6iah** [comment]
Logos updated, unsure how to clarify this in a way other than commenting.

**Comment by isa6iah** [comment]
leadership info updated,
sponsors updated.
general cleanup preformed / numbers updated.
individual team pages have yet to be updated.

**Comment by isa6iah** [comment]
Glad we finally finished
