### ISSUE TITLE
Raspberry Pi Zero HAT Size

### ISSUE THREAD

**Issue by ghost** [m2i/MAVRIC-General#4]
The size of the HAT may be too small for some of our electronics. See b48feaf
Options:
 - Use daughter cards to stack higher
 - Use separate cards to expand horizontally
 - Extend the edges of the PCB past the mounting holes
 - Save some space by going to smaller resistor packages
   - Increases chance of damaging the resistors while soldering

@matgyver Can you grab a quick look?
![layout](https://user-images.githubusercontent.com/13686453/27112164-d4f507ac-507a-11e7-9359-58b907c57a8e.png)

**Comment by matgyver** [comment]
I wouldn't be too worried about damaging the smaller resistors.  Going to a larger board to give room is fine as long as it fits within any other mechanical constraints.  Be careful with stacking, if you are going to use the EEPROM for board identification, I don't think you will be able to stack them.

**Comment by ghost** [comment]
I meant a specific pair, not multiple HATs. The whole stack would function
as a single HAT with 1 EEPROM. I'll bring the resistors down to 0805 then.

**Comment by ghost** [comment]
New Layout:
![layout](https://user-images.githubusercontent.com/13686453/27156182-a1074764-5121-11e7-9531-bdea5c87153c.png)
![rendering](https://user-images.githubusercontent.com/13686453/27156870-aa16036a-5124-11e7-884a-d7d76e8fe17e.png)

see fdbc8f0

**Comment by matgyver** [comment]
that looks good.
