### ISSUE TITLE
PCB Fabrication

### ISSUE THREAD

**Issue by ghost** [m2i/MAVRIC-General#5]
We need to be able to make fairly small runs of boards (say 10) preferably cheaply.
We might be able to use the same board for most of the HATs and just not populate unneeded parts (see #4). This would increase our volume, but also the chance that a revision would fail and need to be re-ordered.

 - What options do we have to manufacture boards?
 - Does M:2:I have any partnerships of university resources?
 - Does anyone have recommendations from personal experience?
 - Are there good ways to verify/test PCBs/designs before ordering?
   - How long does this take? (trade-off between budget and design cycle)
 - Automated simulation testing of PCBs? (is that a thing)

# Options
 - [Advance](http://www.4pcb.com/)
 - [OSHPark](https://oshpark.com/)

**Comment by ghost** [comment]
@matgyver Does the university have any resources for fabricating boards?

**Comment by matgyver** [comment]
@Talonj123 ECpE used to, but I'm not sure if it is still up and running.  M:2:I does have some limited capabilities using our CNC machine.

**Comment by ghost** [comment]
Can M:2:I buy a desktop PCB mill?
 - [OtherMill](https://othermachine.co/othermill)

**Comment by matgyver** [comment]
Maybe, that is something that is beyond this issue thread.  I will look into those options and go from there.
