### ISSUE TITLE
Should we use an RTOS?

### ISSUE THREAD

**Issue by ghost** [m2i/MAVRIC-General#9]
Since we are running on linux, we could use Robot Operating System (ROS).
This would give us the ability to skip some of the low-level control systems code (which is the most fun part to me, but it's time consuming).

Thoughts?

**Comment by ghost** [comment]
ROS Links:
 - http://www.instructables.com/id/Raspberry-Pi-and-ROS-Robotic-Operating-System/
 - http://wiki.ros.org/ROS/Tutorials
 - http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Kinetic%20on%20the%20Raspberry

With ROS, we can operate our boards on a network mostly transparently. Unfortunately, the Zero's do not have an Ethernet port. There are workarounds available to add a port using a SPI.

**Comment by ghost** [comment]
@matgyver, have you ever used an RTOS? Can you comment on the learning curve?
@m2i/mavric-electrical

**Comment by Talonj123** [comment]
http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Kinetic%20on%20the%20Raspberry

**Comment by ghost** [comment]
From Jerry:
If you do use an RTOS [on a microcontroller], don't over-engineer it. Keep the number of tasks small.
 - Consider having the tasks be defined by frequency, so things that aren't time critical get put in a low priority task, but things like reading and saving (but maybe not handling) communication get handled in a high-priority task.
 - Be careful with mutexes and semaphores, they require a context switch, which is slow.
 - For performance critical systems (communication, etc.) consider rolling your own drivers
   - Asynchronous send/receive from/to a circular buffer
   - DMA interfaces if things are still slow
